version: '3.7'
services:
  home-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3223:3223"
    container_name: home-server
    volumes:
       - ./:/usr/src/app
       - /usr/src/app/node_modules
    restart: unless-stopped
    image: home-server:1.0.0